### ISSUE TITLE
Program does not work

### ISSUE THREAD

**Issue by ina111** [sus304/ForRocket#2]
Char_Sheet.xlsxを適当に埋めて、makeでコンパイルをしたのですが、途中で止まってしまいます。
事前にcs2dat.pyを実行して.datファイルの更新もおこいました。
下記のところで止まってしまいます。

```
$ python ForRocket.py
Simulation Start!
cs2data

Calcutate
 Calculation Start!!
        Vw  Vw_angle       Top  Altitude   Landing
```

**Comment by sus304** [comment]
こちらで実行したところ動作しましたので諸元の入力の不適合かと思われます。
calculation startから先に進まない場合は離床しない、着地しないなどが主な原因です。

サンプルデータ(Char_Sheet.xlsx,Mach_Cd.dat)をコミットしましたのでそちらで試してみてください。
高度300 m程度になるはずです。

諸元の詳細な定義や中身などの説明ファイルは近日中に作成予定です。

**Comment by ina111** [comment]
新しいサンプルデータでは動作しました。
ありがとうございます。
離床しないなどの時は例外吐けるようになると良いですね。
